name: Weekly Embeddings

on:
  schedule:
    - cron: "0 3 * * 0"   # every Sunday 3 AM UTC
  workflow_dispatch:

jobs:
  embed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run embed
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
