/**
 * AI-Powered Lead Nurture Sequence API
 * Generates and schedules personalized email sequences using AI
 */

import { NextRequest, NextResponse } from 'next/server';
import { getAdminClient } from '@/lib/supabase/admin';
import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || process.env.CLAUDE_API_KEY || '',
});

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { leadId } = body;

    if (!leadId) {
      return NextResponse.json(
        { error: 'Missing required field: leadId' },
        { status: 400 }
      );
    }

    const supabase = getAdminClient();

    // Fetch complete lead journey data
    const { data: leadData, error: leadError } = await supabase
      .from('leads')
      .select(`
        *,
        property:properties(*),
        builder:builders(*),
        interactions:lead_interactions(*)
      `)
      .eq('id', leadId)
      .single();

    if (leadError || !leadData) {
      return NextResponse.json(
        { error: 'Lead not found' },
        { status: 404 }
      );
    }

    const lead = leadData as any;
    const property = lead.property;
    const builder = lead.builder;
    const interactions = lead.interactions || [];

    // Analyze behavior patterns
    const pageViews = interactions.filter((i: any) => i.type === 'page_view').length;
    const formSubmissions = interactions.filter((i: any) => i.type === 'form_submit').length;
    const emailOpens = interactions.filter((i: any) => i.type === 'email_open').length;
    const engagementScore = (pageViews * 1) + (formSubmissions * 3) + (emailOpens * 2);

    // Determine buyer stage
    let buyerStage = 'awareness';
    if (engagementScore >= 15) buyerStage = 'decision';
    else if (engagementScore >= 5) buyerStage = 'consideration';

    const daysSinceFirstContact = Math.floor(
      (Date.now() - new Date(lead.created_at).getTime()) / (1000 * 60 * 60 * 24)
    );

    // Generate AI content
    const prompt = `You are an expert real estate sales consultant for Tharaga, India's first zero-commission property platform.

Lead Profile:
- Name: ${lead.name || lead.lead_buyer_name}
- Budget: ₹${(lead.budget || lead.estimated_budget || 'Not specified').toLocaleString('en-IN')}
- Preferences: ${JSON.stringify(lead.preferences || {})}
- Lead Score: ${lead.ai_lead_score || 0}/100

Property:
- Name: ${property?.title || property?.property_name}
- Price: ₹${(property?.price_inr || 0).toLocaleString('en-IN')}
- Type: ${property?.property_type || property?.bhk_type}
- Location: ${property?.location || property?.locality || property?.city}

Buyer Stage: ${buyerStage}
Days Since Contact: ${daysSinceFirstContact}
Engagement Score: ${engagementScore}

Recent Interactions:
${JSON.stringify(interactions.slice(0, 10), null, 2)}

Generate a personalized email sequence (3 emails) that:
1. First email (Day 0): Welcome and property highlights matching their preferences
2. Second email (Day 3): Address common objections, local area benefits, similar properties
3. Third email (Day 7): Create urgency, offer exclusive viewing slot, testimonials

For each email, provide:
- day: number (0, 3, or 7)
- subject: string (compelling, personalized, <60 chars)
- html: string (HTML email body, warm tone, 150-250 words, include clear CTA)
- text: string (plain text version)
- cta: string (call-to-action text)

Return ONLY valid JSON in this format:
{
  "emails": [
    {
      "day": 0,
      "subject": "...",
      "html": "...",
      "text": "...",
      "cta": "..."
    }
  ]
}`;

    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 2000,
      messages: [{ role: 'user', content: prompt }]
    });

    const content = response.content[0];
    if (content.type !== 'text') {
      throw new Error('Unexpected response type from AI');
    }

    let responseText = content.text.trim();
    if (responseText.startsWith('```json')) {
      responseText = responseText.replace(/```json\n?/g, '').replace(/```\n?/g, '');
    }

    const aiResponse = JSON.parse(responseText);
    const emails = aiResponse.emails || [];

    if (emails.length === 0) {
      throw new Error('No emails generated by AI');
    }

    // Create sequence schedule
    const sequenceEntries = emails.map((email: any, index: number) => ({
      lead_id: leadId,
      builder_id: builder.id,
      property_id: property?.id || null,
      sequence_position: index + 1,
      scheduled_for: new Date(Date.now() + (email.day * 24 * 60 * 60 * 1000)).toISOString(),
      subject: email.subject,
      html_content: email.html,
      text_content: email.text || email.html.replace(/<[^>]*>/g, ''),
      cta: email.cta,
      status: 'scheduled',
      metadata: {
        buyer_stage: buyerStage,
        engagement_score: engagementScore,
        days_since_contact: daysSinceFirstContact,
        ai_generated: true
      }
    }));

    // Insert into email_sequence_queue
    const { data: inserted, error: insertError } = await supabase
      .from('email_sequence_queue')
      .insert(sequenceEntries)
      .select();

    if (insertError) {
      throw new Error(`Failed to create sequence: ${insertError.message}`);
    }

    return NextResponse.json({
      success: true,
      sequenceCount: inserted?.length || 0,
      scheduledEmails: inserted?.map((e: any) => ({
        position: e.sequence_position,
        scheduledFor: e.scheduled_for,
        subject: e.subject
      }))
    });

  } catch (error: any) {
    console.error('[AI Nurture Sequence] Error:', error);
    return NextResponse.json(
      { error: error.message || 'Internal server error' },
      { status: 500 }
    );
  }
}

