[build]
  command = ""
  publish = "."   # Root folder where your index.html exists

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173   # e.g., Vite dev server
  functionsPort = 9999
  publish = "dist"

# Redirect all routes to index.html (SPA support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Environment variables (you can still set them in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"
  SUPABASE_URL = "https://your-project.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZGV2dGpqbWR2bmd5c2hxZHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NzYwMzgsImV4cCI6MjA3MTA1MjAzOH0.Ex2c_sx358dFdygUGMVBohyTVto6fdEQ5nydDRh9m6M"
