version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tharaga
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  saas:
    build: ./saas-server
    restart: unless-stopped
    env_file:
      - ./saas-server/.env
    environment:
      # Fallbacks if not present in env file
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/tharaga}
      PORT: ${PORT:-4000}
      NODE_ENV: ${NODE_ENV:-development}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    depends_on:
      - db
    ports:
      - "4000:4000"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NODE_ENV: production
    depends_on:
      - saas
    ports:
      - "3000:3000"

volumes:
  db_data:
