services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tharaga
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  saas:
    build: ./saas-server
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/tharaga
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "4000:4000"
    depends_on:
      - db
  app:
    working_dir: /app/app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - saas
volumes:
  dbdata: {}
