warning: in the working copy of '.github/workflows/cron.yml', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'ACTION_BUILDER_IMPLEMENTATION_COMPLETE.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'AI_ANALYSIS_AUTOMATION_SYSTEM.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'AUTOMATION_FILES_RESTORED.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'AUTOMATION_RESTORATION_COMPLETE.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'AUTOMATION_RESTORATION_PLAN.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'AUTOMATION_SYSTEM_COMPLETE.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'AUTOMATION_SYSTEM_FINAL_REPORT.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'CHENNAI_PHASE1_COMPLETE_SUMMARY.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'CHENNAI_PHASE1_FINAL_VALIDATION.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'CHENNAI_PHASE1_IMPLEMENTATION_STATUS.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'COMPLETE_VERIFICATION_SUMMARY.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'COMPREHENSIVE_FEATURE_VERIFICATION_REPORT.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'CRON_ENVIRONMENT_VARIABLES.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'DATA_COLLECTION_IMPLEMENTATION_SUMMARY.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'DEEP_ANALYSIS_RESTORATION_VERIFICATION.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'DELETION_STATUS_REPORT.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'FINAL_DEEP_ANALYSIS_CONFIRMATION.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'FINAL_EXECUTION_SUMMARY.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'FINAL_VERIFICATION_REPORT.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'IMPLEMENTATION_COMPLETE.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'IMPLEMENTATION_QUALITY_AUDIT.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'MIGRATION_EXECUTION_GUIDE.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'MIGRATION_SUCCESS_REPORT.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'README-AUTOMATION-SYSTEM.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'RESTORATION_VALIDATION_REPORT.md', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/automations/[id]/execute/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/automations/[id]/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/automations/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/automations/stats/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/crm/zoho/connect/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/crm/zoho/sync-logs/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/cron/execute/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/cron/preview/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/cron/process-automations/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/cron/validate/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/integrations/zoho/callback/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/integrations/zoho/connect/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/integrations/zoho/disconnect/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/integrations/zoho/status/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/integrations/zoho/sync/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/integrations/zoho/webhook/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/job-logs/[id]/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/job-logs/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/job-queue/cleanup/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/job-queue/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/job-queue/stats/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/properties/[id]/compute-risk-flags/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/properties/[id]/documents/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/rera-snapshot/[id]/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/rzp/create-subscription/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/schedule-templates/[id]/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/schedule-templates/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/schedules/[id]/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/schedules/[id]/trigger/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/schedules/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/app/api/webhooks/endpoints/route.ts', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/components/automation/ActionBuilder.tsx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/components/automation/AutomationDashboard.tsx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/components/automation/AutomationForm.tsx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/components/automation/ConditionBuilder.tsx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/components/automation/ConditionGroup.tsx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'app/components/automation/ConditionRow.tsx', CRLF will be replaced by LF the next time Git touches it
war