[build]
  # This file is loaded when the Netlify site uses base directory = "login_signup_glassdrop"
  # So the publish directory should be the current folder.
  publish = "."
  functions = "../netlify/functions"

[[redirects]]
  from = "/login_signup_glassdrop"
  to = "/"
  status = 301

[[redirects]]
  from = "/login_signup_glassdrop/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone()"
    Content-Security-Policy = "default-src 'self'; img-src 'self' https: data:; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' https://wedevtjjmdvngyshqdro.supabase.co https://www.google.com https://www.googleapis.com https://www.gstatic.com; frame-ancestors 'self' https://tharaga.co.in https://www.tharaga.co.in; frame-src 'self' https://www.google.com https://www.gstatic.com; base-uri 'self'"

