-- Billing entitlements tables
create table if not exists public.org_subscriptions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete cascade,
  email text,
  stripe_customer_id text,
  stripe_price_id text,
  tier text not null check (tier in ('starter','growth','scale')) default 'starter',
  status text not null default 'inactive',
  active_until timestamptz,
  unique(email)
);

create index if not exists idx_org_subs_user on public.org_subscriptions(user_id);
create index if not exists idx_org_subs_email on public.org_subscriptions(email);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

create trigger trg_org_subs_updated
before update on public.org_subscriptions
for each row execute procedure public.set_updated_at();

-- Allow users to view their own subscription row
alter table public.org_subscriptions enable row level security;
create policy "own sub read" on public.org_subscriptions for select using (
  auth.email() = email or auth.uid() = user_id
);

-- Extend schema for provider + subscription id (Razorpay)
do $$ begin
  alter table public.org_subscriptions add column if not exists provider text default 'stripe';
  alter table public.org_subscriptions add column if not exists subscription_id text;
exception when others then null; end $$;
