name: Frontend - Netlify Build & E2E

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'netlify.toml'

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: app
        run: npm ci || npm i
      - name: Build Next.js
        working-directory: app
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: app/.next

  e2e:
    needs: build-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Playwright
        run: |
          npm ci || npm i
          npx playwright install --with-deps
      - name: Run E2E
        env:
          PLAYWRIGHT_BASE_URL: ${{ secrets.E2E_BASE_URL || 'http://localhost:4173' }}
        run: npm run test:e2e
